### ISSUE TITLE
Volunteering as a maintainer

### ISSUE THREAD

**Issue by Kxnr** [devinvs/fuzzydate#10]
Hi @devinvs, I'd love to keep updating/maintaining this package--would you be willing to extend maintainer rights to me (or one of the previous contributors)?

**Comment by devinvs** [comment]
obviously I don't have the energy to keep up with it, you should have an invite in your email

**Comment by Kxnr** [comment]
The curse of building something cool :)

I've obviously fallen behind as well, so we'll see how I do. Should have asked--I'm happy to maintain a fork instead, either under the same crates.io package or a new name. What's your preference?
