### ISSUE TITLE
Specify base datetime for relative specifiers

### ISSUE THREAD

**Issue by Kxnr** [devinvs/fuzzydate#4]
Thanks for creating this library!

I'm using `fuzzydate` for navigation within a personal wiki and would like to be able to specify dates relative to the currently selected date/time, as well as the current date/time. Would you accept a contribution to this effect? I think this would be straightforward to implement by adding a `default` parameter to `to_chrono` on `Date`.

**Comment by devinvs** [comment]
Absolutely! I'm glad this is useful for more than just my personal todo app.

My one request is that the changes are backwards compatible and don't break existing code. In that vein, don't change the types/arguments for `parse` or `parse_with_default_time`, but you can add another method (such as `parse_with_default_date_time`.

Once you submit a pull request I'll try to get you feedback as quickly as possible. Thank You!
